#include "ar_gl.h"

#include <GL/freeglut.h>

#include <stdio.h>
#include <assert.h>

static const char* ar_gl_error_string(GLenum err){
    switch (err){
        case GL_NO_ERROR: return "GL_NO_ERROR";
        case GL_INVALID_ENUM: return "GL_INVALID_ENUM";
        case GL_INVALID_OPERATION: return "GL_INVALID_OPERATION";
        case GL_INVALID_VALUE: return "GL_INVALID_VALUE";
        case GL_OUT_OF_MEMORY: return "GL_OUT_OF_MEMORY";
        default: return "Unknown OpenGL error";
    }
}

void ar_gl_check(int line){
    GLenum err = glGetError();
    if (err != GL_NO_ERROR){
        printf("Line %i: %s\n", line, ar_gl_error_string(err));
    }
}

#ifdef _WIN32

ar_gl_func_ptr ar_gl_get_proc_address(const char *name){
    return (ar_gl_func_ptr)wglGetProcAddress(name);
}

PFNGLACTIVETEXTUREPROC ar_glActiveTexture;
PFNGLATTACHSHADERPROC ar_glAttachShader;
PFNGLBINDATTRIBLOCATIONPROC ar_glBindAttribLocation;
PFNGLBINDBUFFERPROC ar_glBindBuffer;
PFNGLBINDFRAMEBUFFERPROC ar_glBindFramebuffer;
PFNGLBINDRENDERBUFFERPROC ar_glBindRenderbuffer;
PFNGLBINDTEXTUREPROC ar_glBindTexture;
PFNGLBLENDCOLORPROC ar_glBlendColor;
PFNGLBLENDEQUATIONPROC ar_glBlendEquation;
PFNGLBLENDEQUATIONSEPARATEPROC ar_glBlendEquationSeparate;
PFNGLBLENDFUNCPROC ar_glBlendFunc;
PFNGLBLENDFUNCSEPARATEPROC ar_glBlendFuncSeparate;
PFNGLBUFFERDATAPROC ar_glBufferData;
PFNGLBUFFERSUBDATAPROC ar_glBufferSubData;
PFNGLCHECKFRAMEBUFFERSTATUSPROC ar_glCheckFramebufferStatus;
PFNGLCLEARPROC ar_glClear;
PFNGLCLEARCOLORPROC ar_glClearColor;
PFNGLCLEARDEPTHFPROC ar_glClearDepthf;
PFNGLCLEARSTENCILPROC ar_glClearStencil;
PFNGLCOLORMASKPROC ar_glColorMask;
PFNGLCOMPILESHADERPROC ar_glCompileShader;
PFNGLCOMPRESSEDTEXIMAGE2DPROC ar_glCompressedTexImage2D;
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC ar_glCompressedTexSubImage2D;
PFNGLCOPYTEXIMAGE2DPROC ar_glCopyTexImage2D;
PFNGLCOPYTEXSUBIMAGE2DPROC ar_glCopyTexSubImage2D;
PFNGLCREATEPROGRAMPROC ar_glCreateProgram;
PFNGLCREATESHADERPROC ar_glCreateShader;
PFNGLCULLFACEPROC ar_glCullFace;
PFNGLDELETEBUFFERSPROC ar_glDeleteBuffers;
PFNGLDELETEFRAMEBUFFERSPROC ar_glDeleteFramebuffers;
PFNGLDELETEPROGRAMPROC ar_glDeleteProgram;
PFNGLDELETERENDERBUFFERSPROC ar_glDeleteRenderbuffers;
PFNGLDELETESHADERPROC ar_glDeleteShader;
PFNGLDELETETEXTURESPROC ar_glDeleteTextures;
PFNGLDEPTHFUNCPROC ar_glDepthFunc;
PFNGLDEPTHMASKPROC ar_glDepthMask;
PFNGLDEPTHRANGEFPROC ar_glDepthRangef;
PFNGLDETACHSHADERPROC ar_glDetachShader;
PFNGLDISABLEPROC ar_glDisable;
PFNGLDISABLEVERTEXATTRIBARRAYPROC ar_glDisableVertexAttribArray;
PFNGLDRAWARRAYSPROC ar_glDrawArrays;
PFNGLDRAWELEMENTSPROC ar_glDrawElements;
PFNGLENABLEPROC ar_glEnable;
PFNGLENABLEVERTEXATTRIBARRAYPROC ar_glEnableVertexAttribArray;
PFNGLFINISHPROC ar_glFinish;
PFNGLFLUSHPROC ar_glFlush;
PFNGLFRAMEBUFFERRENDERBUFFERPROC ar_glFramebufferRenderbuffer;
PFNGLFRAMEBUFFERTEXTURE2DPROC ar_glFramebufferTexture2D;
PFNGLFRONTFACEPROC ar_glFrontFace;
PFNGLGENBUFFERSPROC ar_glGenBuffers;
PFNGLGENFRAMEBUFFERSPROC ar_glGenFramebuffers;
PFNGLGENRENDERBUFFERSPROC ar_glGenRenderbuffers;
PFNGLGENTEXTURESPROC ar_glGenTextures;
PFNGLGENERATEMIPMAPPROC ar_glGenerateMipmap;
PFNGLGETACTIVEATTRIBPROC ar_glGetActiveAttrib;
PFNGLGETACTIVEUNIFORMPROC ar_glGetActiveUniform;
PFNGLGETATTACHEDSHADERSPROC ar_glGetAttachedShaders;
PFNGLGETATTRIBLOCATIONPROC ar_glGetAttribLocation;
PFNGLGETBOOLEANVPROC ar_glGetBooleanv;
PFNGLGETBUFFERPARAMETERIVPROC ar_glGetBufferParameteriv;
PFNGLGETERRORPROC ar_glGetError;
PFNGLGETFLOATVPROC ar_glGetFloatv;
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC ar_glGetFramebufferAttachmentParameteriv;
PFNGLGETINTEGERVPROC ar_glGetIntegerv;
PFNGLGETPROGRAMINFOLOGPROC ar_glGetProgramInfoLog;
PFNGLGETPROGRAMIVPROC ar_glGetProgramiv;
PFNGLGETRENDERBUFFERPARAMETERIVPROC ar_glGetRenderbufferParameteriv;
PFNGLGETSHADERINFOLOGPROC ar_glGetShaderInfoLog;
PFNGLGETSHADERPRECISIONFORMATPROC ar_glGetShaderPrecisionFormat;
PFNGLGETSHADERSOURCEPROC ar_glGetShaderSource;
PFNGLGETSHADERIVPROC ar_glGetShaderiv;
PFNGLGETSTRINGPROC ar_glGetString;
PFNGLGETTEXPARAMETERFVPROC ar_glGetTexParameterfv;
PFNGLGETTEXPARAMETERIVPROC ar_glGetTexParameteriv;
PFNGLGETUNIFORMLOCATIONPROC ar_glGetUniformLocation;
PFNGLGETUNIFORMFVPROC ar_glGetUniformfv;
PFNGLGETUNIFORMIVPROC ar_glGetUniformiv;
PFNGLGETVERTEXATTRIBPOINTERVPROC ar_glGetVertexAttribPointerv;
PFNGLGETVERTEXATTRIBFVPROC ar_glGetVertexAttribfv;
PFNGLGETVERTEXATTRIBIVPROC ar_glGetVertexAttribiv;
PFNGLHINTPROC ar_glHint;
PFNGLISBUFFERPROC ar_glIsBuffer;
PFNGLISENABLEDPROC ar_glIsEnabled;
PFNGLISFRAMEBUFFERPROC ar_glIsFramebuffer;
PFNGLISPROGRAMPROC ar_glIsProgram;
PFNGLISRENDERBUFFERPROC ar_glIsRenderbuffer;
PFNGLISSHADERPROC ar_glIsShader;
PFNGLISTEXTUREPROC ar_glIsTexture;
PFNGLLINEWIDTHPROC ar_glLineWidth;
PFNGLLINKPROGRAMPROC ar_glLinkProgram;
PFNGLPIXELSTOREIPROC ar_glPixelStorei;
PFNGLPOLYGONOFFSETPROC ar_glPolygonOffset;
PFNGLREADPIXELSPROC ar_glReadPixels;
PFNGLRELEASESHADERCOMPILERPROC ar_glReleaseShaderCompiler;
PFNGLRENDERBUFFERSTORAGEPROC ar_glRenderbufferStorage;
PFNGLSAMPLECOVERAGEPROC ar_glSampleCoverage;
PFNGLSCISSORPROC ar_glScissor;
PFNGLSHADERBINARYPROC ar_glShaderBinary;
PFNGLSHADERSOURCEPROC ar_glShaderSource;
PFNGLSTENCILFUNCPROC ar_glStencilFunc;
PFNGLSTENCILFUNCSEPARATEPROC ar_glStencilFuncSeparate;
PFNGLSTENCILMASKPROC ar_glStencilMask;
PFNGLSTENCILMASKSEPARATEPROC ar_glStencilMaskSeparate;
PFNGLSTENCILOPPROC ar_glStencilOp;
PFNGLSTENCILOPSEPARATEPROC ar_glStencilOpSeparate;
PFNGLTEXIMAGE2DPROC ar_glTexImage2D;
PFNGLTEXPARAMETERFPROC ar_glTexParameterf;
PFNGLTEXPARAMETERFVPROC ar_glTexParameterfv;
PFNGLTEXPARAMETERIPROC ar_glTexParameteri;
PFNGLTEXPARAMETERIVPROC ar_glTexParameteriv;
PFNGLTEXSUBIMAGE2DPROC ar_glTexSubImage2D;
PFNGLUNIFORM1FPROC ar_glUniform1f;
PFNGLUNIFORM1FVPROC ar_glUniform1fv;
PFNGLUNIFORM1IPROC ar_glUniform1i;
PFNGLUNIFORM1IVPROC ar_glUniform1iv;
PFNGLUNIFORM2FPROC ar_glUniform2f;
PFNGLUNIFORM2FVPROC ar_glUniform2fv;
PFNGLUNIFORM2IPROC ar_glUniform2i;
PFNGLUNIFORM2IVPROC ar_glUniform2iv;
PFNGLUNIFORM3FPROC ar_glUniform3f;
PFNGLUNIFORM3FVPROC ar_glUniform3fv;
PFNGLUNIFORM3IPROC ar_glUniform3i;
PFNGLUNIFORM3IVPROC ar_glUniform3iv;
PFNGLUNIFORM4FPROC ar_glUniform4f;
PFNGLUNIFORM4FVPROC ar_glUniform4fv;
PFNGLUNIFORM4IPROC ar_glUniform4i;
PFNGLUNIFORM4IVPROC ar_glUniform4iv;
PFNGLUNIFORMMATRIX2FVPROC ar_glUniformMatrix2fv;
PFNGLUNIFORMMATRIX3FVPROC ar_glUniformMatrix3fv;
PFNGLUNIFORMMATRIX4FVPROC ar_glUniformMatrix4fv;
PFNGLUSEPROGRAMPROC ar_glUseProgram;
PFNGLVALIDATEPROGRAMPROC ar_glValidateProgram;
PFNGLVERTEXATTRIB1FPROC ar_glVertexAttrib1f;
PFNGLVERTEXATTRIB1FVPROC ar_glVertexAttrib1fv;
PFNGLVERTEXATTRIB2FPROC ar_glVertexAttrib2f;
PFNGLVERTEXATTRIB2FVPROC ar_glVertexAttrib2fv;
PFNGLVERTEXATTRIB3FPROC ar_glVertexAttrib3f;
PFNGLVERTEXATTRIB3FVPROC ar_glVertexAttrib3fv;
PFNGLVERTEXATTRIB4FPROC ar_glVertexAttrib4f;
PFNGLVERTEXATTRIB4FVPROC ar_glVertexAttrib4fv;
PFNGLVERTEXATTRIBPOINTERPROC ar_glVertexAttribPointer;
PFNGLVIEWPORTPROC ar_glViewport;

#define AR_LOAD(func, ptr_func) ar_##func = (ptr_func)ar_gl_get_proc_address(#func); assert(ar_##func);

void ar_gl_init(void){
    AR_LOAD(glActiveTexture, PFNGLACTIVETEXTUREPROC)
    AR_LOAD(glAttachShader, PFNGLATTACHSHADERPROC)
    AR_LOAD(glBindAttribLocation, PFNGLBINDATTRIBLOCATIONPROC)
    AR_LOAD(glBindBuffer, PFNGLBINDBUFFERPROC)
    AR_LOAD(glBindFramebuffer, PFNGLBINDFRAMEBUFFERPROC)
    AR_LOAD(glBindRenderbuffer, PFNGLBINDRENDERBUFFERPROC)
    AR_LOAD(glBindTexture, PFNGLBINDTEXTUREPROC)
    AR_LOAD(glBlendColor, PFNGLBLENDCOLORPROC)
    AR_LOAD(glBlendEquation, PFNGLBLENDEQUATIONPROC)
    AR_LOAD(glBlendEquationSeparate, PFNGLBLENDEQUATIONSEPARATEPROC)
    AR_LOAD(glBlendFunc, PFNGLBLENDFUNCPROC)
    AR_LOAD(glBlendFuncSeparate, PFNGLBLENDFUNCSEPARATEPROC)
    AR_LOAD(glBufferData, PFNGLBUFFERDATAPROC)
    AR_LOAD(glBufferSubData, PFNGLBUFFERSUBDATAPROC)
    AR_LOAD(glCheckFramebufferStatus, PFNGLCHECKFRAMEBUFFERSTATUSPROC)
    AR_LOAD(glClear, PFNGLCLEARPROC)
    AR_LOAD(glClearColor, PFNGLCLEARCOLORPROC)
    AR_LOAD(glClearDepthf, PFNGLCLEARDEPTHFPROC)
    AR_LOAD(glClearStencil, PFNGLCLEARSTENCILPROC)
    AR_LOAD(glColorMask, PFNGLCOLORMASKPROC)
    AR_LOAD(glCompileShader, PFNGLCOMPILESHADERPROC)
    AR_LOAD(glCompressedTexImage2D, PFNGLCOMPRESSEDTEXIMAGE2DPROC)
    AR_LOAD(glCompressedTexSubImage2D, PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC)
    AR_LOAD(glCopyTexImage2D, PFNGLCOPYTEXIMAGE2DPROC)
    AR_LOAD(glCopyTexSubImage2D, PFNGLCOPYTEXSUBIMAGE2DPROC)
    AR_LOAD(glCreateProgram, PFNGLCREATEPROGRAMPROC)
    AR_LOAD(glCreateShader, PFNGLCREATESHADERPROC)
    AR_LOAD(glCullFace, PFNGLCULLFACEPROC)
    AR_LOAD(glDeleteBuffers, PFNGLDELETEBUFFERSPROC)
    AR_LOAD(glDeleteFramebuffers, PFNGLDELETEFRAMEBUFFERSPROC)
    AR_LOAD(glDeleteProgram, PFNGLDELETEPROGRAMPROC)
    AR_LOAD(glDeleteRenderbuffers, PFNGLDELETERENDERBUFFERSPROC)
    AR_LOAD(glDeleteShader, PFNGLDELETESHADERPROC)
    AR_LOAD(glDeleteTextures, PFNGLDELETETEXTURESPROC)
    AR_LOAD(glDepthFunc, PFNGLDEPTHFUNCPROC)
    AR_LOAD(glDepthMask, PFNGLDEPTHMASKPROC)
    AR_LOAD(glDepthRangef, PFNGLDEPTHRANGEFPROC)
    AR_LOAD(glDetachShader, PFNGLDETACHSHADERPROC)
    AR_LOAD(glDisable, PFNGLDISABLEPROC)
    AR_LOAD(glDisableVertexAttribArray, PFNGLDISABLEVERTEXATTRIBARRAYPROC)
    AR_LOAD(glDrawArrays, PFNGLDRAWARRAYSPROC)
    AR_LOAD(glDrawElements, PFNGLDRAWELEMENTSPROC)
    AR_LOAD(glEnable, PFNGLENABLEPROC)
    AR_LOAD(glEnableVertexAttribArray, PFNGLENABLEVERTEXATTRIBARRAYPROC)
    AR_LOAD(glFinish, PFNGLFINISHPROC)
    AR_LOAD(glFlush, PFNGLFLUSHPROC)
    AR_LOAD(glFramebufferRenderbuffer, PFNGLFRAMEBUFFERRENDERBUFFERPROC)
    AR_LOAD(glFramebufferTexture2D, PFNGLFRAMEBUFFERTEXTURE2DPROC)
    AR_LOAD(glFrontFace, PFNGLFRONTFACEPROC)
    AR_LOAD(glGenBuffers, PFNGLGENBUFFERSPROC)
    AR_LOAD(glGenFramebuffers, PFNGLGENFRAMEBUFFERSPROC)
    AR_LOAD(glGenRenderbuffers, PFNGLGENRENDERBUFFERSPROC)
    AR_LOAD(glGenTextures, PFNGLGENTEXTURESPROC)
    AR_LOAD(glGenerateMipmap, PFNGLGENERATEMIPMAPPROC)
    AR_LOAD(glGetActiveAttrib, PFNGLGETACTIVEATTRIBPROC)
    AR_LOAD(glGetActiveUniform, PFNGLGETACTIVEUNIFORMPROC)
    AR_LOAD(glGetAttachedShaders, PFNGLGETATTACHEDSHADERSPROC)
    AR_LOAD(glGetAttribLocation, PFNGLGETATTRIBLOCATIONPROC)
    AR_LOAD(glGetBooleanv, PFNGLGETBOOLEANVPROC)
    AR_LOAD(glGetBufferParameteriv, PFNGLGETBUFFERPARAMETERIVPROC)
    AR_LOAD(glGetError, PFNGLGETERRORPROC)
    AR_LOAD(glGetFloatv, PFNGLGETFLOATVPROC)
    AR_LOAD(glGetFramebufferAttachmentParameteriv, PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC)
    AR_LOAD(glGetIntegerv, PFNGLGETINTEGERVPROC)
    AR_LOAD(glGetProgramInfoLog, PFNGLGETPROGRAMINFOLOGPROC)
    AR_LOAD(glGetProgramiv, PFNGLGETPROGRAMIVPROC)
    AR_LOAD(glGetRenderbufferParameteriv, PFNGLGETRENDERBUFFERPARAMETERIVPROC)
    AR_LOAD(glGetShaderInfoLog, PFNGLGETSHADERINFOLOGPROC)
    AR_LOAD(glGetShaderPrecisionFormat, PFNGLGETSHADERPRECISIONFORMATPROC)
    AR_LOAD(glGetShaderSource, PFNGLGETSHADERSOURCEPROC)
    AR_LOAD(glGetShaderiv, PFNGLGETSHADERIVPROC)
    AR_LOAD(glGetString, PFNGLGETSTRINGPROC)
    AR_LOAD(glGetTexParameterfv, PFNGLGETTEXPARAMETERFVPROC)
    AR_LOAD(glGetTexParameteriv, PFNGLGETTEXPARAMETERIVPROC)
    AR_LOAD(glGetUniformLocation, PFNGLGETUNIFORMLOCATIONPROC)
    AR_LOAD(glGetUniformfv, PFNGLGETUNIFORMFVPROC)
    AR_LOAD(glGetUniformiv, PFNGLGETUNIFORMIVPROC)
    AR_LOAD(glGetVertexAttribPointerv, PFNGLGETVERTEXATTRIBPOINTERVPROC)
    AR_LOAD(glGetVertexAttribfv, PFNGLGETVERTEXATTRIBFVPROC)
    AR_LOAD(glGetVertexAttribiv, PFNGLGETVERTEXATTRIBIVPROC)
    AR_LOAD(glHint, PFNGLHINTPROC)
    AR_LOAD(glIsBuffer, PFNGLISBUFFERPROC)
    AR_LOAD(glIsEnabled, PFNGLISENABLEDPROC)
    AR_LOAD(glIsFramebuffer, PFNGLISFRAMEBUFFERPROC)
    AR_LOAD(glIsProgram, PFNGLISPROGRAMPROC)
    AR_LOAD(glIsRenderbuffer, PFNGLISRENDERBUFFERPROC)
    AR_LOAD(glIsShader, PFNGLISSHADERPROC)
    AR_LOAD(glIsTexture, PFNGLISTEXTUREPROC)
    AR_LOAD(glLineWidth, PFNGLLINEWIDTHPROC)
    AR_LOAD(glLinkProgram, PFNGLLINKPROGRAMPROC)
    AR_LOAD(glPixelStorei, PFNGLPIXELSTOREIPROC)
    AR_LOAD(glPolygonOffset, PFNGLPOLYGONOFFSETPROC)
    AR_LOAD(glReadPixels, PFNGLREADPIXELSPROC)
    AR_LOAD(glReleaseShaderCompiler, PFNGLRELEASESHADERCOMPILERPROC)
    AR_LOAD(glRenderbufferStorage, PFNGLRENDERBUFFERSTORAGEPROC)
    AR_LOAD(glSampleCoverage, PFNGLSAMPLECOVERAGEPROC)
    AR_LOAD(glScissor, PFNGLSCISSORPROC)
    AR_LOAD(glShaderBinary, PFNGLSHADERBINARYPROC)
    AR_LOAD(glShaderSource, PFNGLSHADERSOURCEPROC)
    AR_LOAD(glStencilFunc, PFNGLSTENCILFUNCPROC)
    AR_LOAD(glStencilFuncSeparate, PFNGLSTENCILFUNCSEPARATEPROC)
    AR_LOAD(glStencilMask, PFNGLSTENCILMASKPROC)
    AR_LOAD(glStencilMaskSeparate, PFNGLSTENCILMASKSEPARATEPROC)
    AR_LOAD(glStencilOp, PFNGLSTENCILOPPROC)
    AR_LOAD(glStencilOpSeparate, PFNGLSTENCILOPSEPARATEPROC)
    AR_LOAD(glTexImage2D, PFNGLTEXIMAGE2DPROC)
    AR_LOAD(glTexParameterf, PFNGLTEXPARAMETERFPROC)
    AR_LOAD(glTexParameterfv, PFNGLTEXPARAMETERFVPROC)
    AR_LOAD(glTexParameteri, PFNGLTEXPARAMETERIPROC)
    AR_LOAD(glTexParameteriv, PFNGLTEXPARAMETERIVPROC)
    AR_LOAD(glTexSubImage2D, PFNGLTEXSUBIMAGE2DPROC)
    AR_LOAD(glUniform1f, PFNGLUNIFORM1FPROC)
    AR_LOAD(glUniform1fv, PFNGLUNIFORM1FVPROC)
    AR_LOAD(glUniform1i, PFNGLUNIFORM1IPROC)
    AR_LOAD(glUniform1iv, PFNGLUNIFORM1IVPROC)
    AR_LOAD(glUniform2f, PFNGLUNIFORM2FPROC)
    AR_LOAD(glUniform2fv, PFNGLUNIFORM2FVPROC)
    AR_LOAD(glUniform2i, PFNGLUNIFORM2IPROC)
    AR_LOAD(glUniform2iv, PFNGLUNIFORM2IVPROC)
    AR_LOAD(glUniform3f, PFNGLUNIFORM3FPROC)
    AR_LOAD(glUniform3fv, PFNGLUNIFORM3FVPROC)
    AR_LOAD(glUniform3i, PFNGLUNIFORM3IPROC)
    AR_LOAD(glUniform3iv, PFNGLUNIFORM3IVPROC)
    AR_LOAD(glUniform4f, PFNGLUNIFORM4FPROC)
    AR_LOAD(glUniform4fv, PFNGLUNIFORM4FVPROC)
    AR_LOAD(glUniform4i, PFNGLUNIFORM4IPROC)
    AR_LOAD(glUniform4iv, PFNGLUNIFORM4IVPROC)
    AR_LOAD(glUniformMatrix2fv, PFNGLUNIFORMMATRIX2FVPROC)
    AR_LOAD(glUniformMatrix3fv, PFNGLUNIFORMMATRIX3FVPROC)
    AR_LOAD(glUniformMatrix4fv, PFNGLUNIFORMMATRIX4FVPROC)
    AR_LOAD(glUseProgram, PFNGLUSEPROGRAMPROC)
    AR_LOAD(glValidateProgram, PFNGLVALIDATEPROGRAMPROC)
    AR_LOAD(glVertexAttrib1f, PFNGLVERTEXATTRIB1FPROC)
    AR_LOAD(glVertexAttrib1fv, PFNGLVERTEXATTRIB1FVPROC)
    AR_LOAD(glVertexAttrib2f, PFNGLVERTEXATTRIB2FPROC)
    AR_LOAD(glVertexAttrib2fv, PFNGLVERTEXATTRIB2FVPROC)
    AR_LOAD(glVertexAttrib3f, PFNGLVERTEXATTRIB3FPROC)
    AR_LOAD(glVertexAttrib3fv, PFNGLVERTEXATTRIB3FVPROC)
    AR_LOAD(glVertexAttrib4f, PFNGLVERTEXATTRIB4FPROC)
    AR_LOAD(glVertexAttrib4fv, PFNGLVERTEXATTRIB4FVPROC)
    AR_LOAD(glVertexAttribPointer, PFNGLVERTEXATTRIBPOINTERPROC)
    AR_LOAD(glViewport, PFNGLVIEWPORTPROC)
}

#else

void ar_gl_init(){

}

#endif
